# Netlify Configuration for scintilla.world
[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Allow extensions folder to be accessible
[[redirects]]
  from = "/extensions/*"
  to = "/extensions/:splat"
  status = 200
  force = false

# Allow tools folder to be accessible
[[redirects]]
  from = "/tools/*"
  to = "/tools/:splat"
  status = 200
  force = false

[context.production.environment]
  NODE_ENV = "production"

